Add

diff --git a/theos b/theos
--- a/theos
+++ b/theos
@@ -2,7 +2,7 @@
 
 need=""
 
-macosDepCheck()
+macosInit()
 {
     command -v fakeroot >/dev/null 2>&1 || need+="fakeroot "
     command -v curl >/dev/null 2>&1 || need+="curl "
@@ -19,7 +19,7 @@ macosDepCheck()
     fi
 }
 
-linuxDepCheck()
+linuxInit()
 {
     command -v fakeroot >/dev/null 2>&1 || need+="fakeroot "
     command -v curl >/dev/null 2>&1 || need+="curl "
@@ -43,14 +43,12 @@ linuxDepCheck()
     fi
 }
 
-distr=$(uname -s)
-arch=$(uname -p)
-if [ "$distr" == "Darwin" ]; then 
-    macosDepCheck
-else linuxDepCheck
+if [ "$(uname -s)" == "Darwin" ]; then 
+    macosInit
+else linuxInit
 fi
 
-if [ $SHELL == "/bin/zsh" ]; then 
+if [ $SHELL == "/usr/bin/zsh" ]; then 
   profile="~/.zshrc"
 else
   profile="~/.bashrc"
@@ -85,14 +83,13 @@ update()
     echo ""
 }
 
-usage()
-{
+usage() {
     echo ""
     echo -e "${CYA}THEOS${NC}"
     echo -e "${YE}usage: theos [commands]${NC}"
     echo ""
     echo -e "${CYA}BUILDING${NC}"
-    echo -e "${VI}-b | --build${NC} | Builds a package. (Put any build commands **after** the command (i.e. theos b FINALPACKAGE=1))"
+    echo -e "${VI}-b | --build${NC} | Builds a package. (Put any build commands after the command (i.e. theos -b FINALPACKAGE=1))"
     echo ""
     echo -e "${CYA}MISC${NC}"
     echo -e "${VI}-ch | --checkra1n${NC} | Opens checkra1n."
@@ -115,12 +112,6 @@ usage()
     echo ""
     echo -e "${VI}-i | --install${NC} | Installs Theos."
     echo ""
-}
-
-checkra1n()
-{
-    command -v checkra1n > /dev/null 2>&1 || echo "Checkra1n is not installed." exit 1
-    fakeroot checkra1n
 }
 
 install()
@@ -165,13 +156,13 @@ while [ "$1" != "" ]; do
     case $1 in
         -dr | --devicerun )        
         shift
-        ssh root@$THEOS_DEVICE_IP "$*"
+        ssh root@$THEOS_DEVICE_IP "$*" || echo "SSH could not open because THEOS_DEVICE_IP is not set up, or some other error occured."
         ;;
         -u | --update)
         update
         ;;
         -ch | --checkra1n)         
-        checkra1n || echo "Checkra1n could not open because you do not have it installed."
+        fakeroot checkra1n || echo "Checkra1n could not open because you do not have it installed."
         ;;
         -n | --nic)                
         $THEOS/bin/nic.pl
@@ -188,18 +179,18 @@ while [ "$1" != "" ]; do
         install
         ;;
         -s | --ssh)                
-        ssh mobile@$THEOS_DEVICE_IP
+        ssh mobile@$THEOS_DEVICE_IP || echo "SSH could not open because THEOS_DEVICE_IP is not set up, or some other error occured."
         exit
         ;;
         -r | --respring)           
-        ssh root@$THEOS_DEVICE_IP "killall SpringBoard" > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up."
+        ssh root@$THEOS_DEVICE_IP "killall SpringBoard" > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up, or some other error occured."
         ;;
         -v | --version)            
         echo -e "${CYA}VERSION${NC}" && echo -e "${YE}1.0.2${NC}"
         ;;
         * )                     
         usage
-        exit 1
+        exit
     esac
     shift
 done
