update installer

diff --git a/theos b/theos
--- a/theos
+++ b/theos
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+final=0
+finalpackage="n"
+do=0
+DO=""
+
 x=$PWD
 
 NC='\033[0m'                            # No Color.
@@ -26,6 +31,7 @@ update()
     git pull
     git submodule update --init --recursive
     cd $x || exit
+    echo ""
 }
 
 usage()
@@ -35,30 +41,30 @@ usage()
     echo -e "${YE}usage: theos [commands]${NC}"
     echo ""
     echo -e "${CYA}BUILDING${NC}"
-    echo -e "${VI}-b | --build${NC} | Builds a package. (Put any variables you'd like to pass to the compiler after the command)"
+    echo -e "${VI}b | build${NC} | Builds a package. (Put any build commands **before** the b flag (i.e. theos final do build))"
     echo ""
     echo -e "${CYA}MISC${NC}"
-    echo -e "${VI}-c | --checkra1n${NC} | Opens checkra1n."
+    echo -e "${VI}ch | checkra1n${NC} | Opens checkra1n."
     echo ""
-    echo -e "${VI}-s | --ssh${NC} | SSH to the IP that you selected."
+    echo -e "${VI}s | ssh${NC} | SSH to the IP that you selected."
     echo ""
-    echo -e "${VI}-dr | --devicerun${NC} | Run a command on the device's IP that you selected."
+    echo -e "${VI}r | respring${NC} | Resprings on your development device."
     echo ""
-    echo -e "${VI}-r | --respring${NC} | Resprings on your development device."
+    echo -e "${VI}dr | devicerun${NC} | Runs selected command on your development device."
     echo ""
-    echo -e "${VI}-rl | --rlog${NC} | Opens RLog."
+    echo -e "${VI}rl | rlog${NC} | Opens RLog."
     echo ""
     echo -e "${CYA}CONFIG${NC}"
-    echo -e "${VI}-u | --update${NC} | Updates Theos."
+    echo -e "${VI}u | update${NC} | Updates Theos."
     echo ""
-    echo -e "${VI}-n | --nic${NC} | Runs nic.pl." 
+    echo -e "${VI}n | nic${NC} | Runs nic.pl." 
     echo ""
-    echo -e "${VI}-v | --version${NC} | Displays the script's version."
+    echo -e "${VI}v | version${NC} | Displays the script's version."
     echo ""
     echo -e "${CYA}INSTALL${NC}"
-    echo -e "${VI}-cl | --clang${NC} | Installs the latest clang toolchain."
+    echo -e "${VI}cl | clang${NC} | Installs the latest clang toolchain."
     echo ""
-    echo -e "${VI}-inst | --install${NC} | Installs Theos."
+    echo -e "${VI}inst | install${NC} | Installs Theos."
     echo ""
 }
 
@@ -71,13 +77,19 @@ install()
 {
     echo -e "${CYA}Instantiating variables...${NC}"
     distr=$(uname -s)
-    arch=$(uname -p)
-    if [ "$distr" == "Darwin" ]; then 
-        echo "export THEOS=~/theos" >> ~/.zprofile
-        echo "export THEOS=~/theos" >> ~/.zshrc
-    else 
-        echo "export THEOS=~/theos" >> ~/.profile
-        echo "export THEOS=~/theos" >> ~/.bashrc
+    if [ $THEOS != "" ]; then
+        theos=$THEOS
+        fakeroot rm -rf $theos
+        restart=0
+    else
+        if [ "$distr" == "Darwin" ]; then 
+            echo "export THEOS=~/theos" >> ~/.zprofile
+            echo "export THEOS=~/theos" >> ~/.zshrc
+        else 
+            echo "export THEOS=~/theos" >> ~/.profile
+            echo "export THEOS=~/theos" >> ~/.bashrc
+        fi
+        restart=1
     fi
     echo -e "${CYA}Cloning theos...${NC}"
     git clone --recursive https://github.com/theos/theos.git $HOME/theos
@@ -93,49 +105,59 @@ install()
     echo -e "${CYA}Getting SDKs...${NC}"
     git clone https://github.com/xybp888/iOS-SDKS $HOME/theos/sdks
     cd $x
-    echo -e "${CYA}Installation is done. In order for the theos variable to take place, you must restart your terminal.${NC}"
+    if [ $restart == 1 ]; then
+        echo -e "${CYA}Installation is done. In order for the theos variable to take place, you must restart your terminal.${NC}"
+    else
+        echo -e "${CYA}Installation is done.${NC}"
+    fi
 }
-
-while [ "$1" != "" ]; do
-    case $1 in
-        -u | --update)              update
-                                exit
-                                ;;
-        -c | --checkra1n)           checkra1n || echo "Checkra1n could not open because you do not have it installed."
-                                exit
-                                ;;
-        -n | --nic)                 $THEOS/bin/nic.pl
-                                exit
-                                ;;
-        -b | --build)               make package $*
-                                exit
-                                ;;
-        -cl | --clang)              fakeroot bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
-                                exit
-                                ;;
-        -inst | --install)          install
-                                exit
-                                ;;
-        -s | --ssh)                 ssh mobile@$THEOS_DEVICE_IP > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up."
-                                exit
-                                ;;
-        -dr | --devicerun)      shift
-                                    ssh root@$THEOS_DEVICE_IP "$*" > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up."
-                                exit
-                                ;;
-        -r | --respring)            ssh root@$THEOS_DEVICE_IP "killall SpringBoard" > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up."
-                                exit
-                                ;;
-        -v | --version)             echo -e "${YE}1.0.1${NC}"
-                                exit
-                                ;;
-        -rl | --rlog)               python $HOME/theosscript/rlogserver.py
-                                ;;
-    esac
-    shift
-done
 
 if [ "$1" == "" ]; then
   usage
   exit
 fi
+
+while [ "$1" != "" ]; do
+    case $1 in
+        u | update)
+        update
+        ;;
+        ch | checkra1n)         
+        checkra1n || echo "Checkra1n could not open because you do not have it installed."
+        ;;
+        n | nic)                
+        $THEOS/bin/nic.pl
+        ;;
+        dr | devicerun )        
+        ssh root@$DRBIP "$*"
+        ;;
+        b | build)
+        shift
+        make package $*
+        exit
+        ;;
+        cl | clang)             
+        fakeroot bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
+        ;;
+        inst | install)         
+        install
+        ;;
+        s | ssh)                
+        ssh mobile@$THEOS_DEVICE_IP > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up."
+        exit
+        ;;
+        r | respring)           
+        ssh root@$THEOS_DEVICE_IP "killall SpringBoard" > /dev/null 2>&1 || echo "SSH could not open because THEOS_DEVICE_IP is not set up."
+        ;;
+        v | version)            
+        echo -e "${CYA}VERSION${NC}" && echo -e "${YE}1.0.1${NC}"
+        ;;
+        rl | rlog)              
+        python $HOME/theosscript/rlogserver.py
+        ;;
+        * )                     
+        usage
+        exit 1
+    esac
+    shift
+done
